authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
    path(
        "courses/",
        cache_page(60 * 5)(views.CoursesListView.as_view()),  # 5 minutes
        name="courses",
    ),
    path(
        "courses/<int:pk>/",
        views.CoursesDetailView.as_view(),
        name="courses_detail",
    ),
    path(
        "course_feedback/",
        views.CourseFeedbackFormProcessView.as_view(),
        name="course_feedback",
    ),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>
      {% block title %}
        Welcome to Braniac!
      {% endblock title %}
    </title>
  </head>

  <body>

    {% include 'includes/main_menu.html' %}

    {% block messages %}
      {% include 'includes/messages.html' %}
    {% endblock messages %}

    <div class="container-md">

      {% block content %}

        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur
        optio est esse? Veritatis laborum expedita
        quibusdam numquam! Expedita amet nisi dolor similique autem, mollitia
        ipsa et, natus vel explicabo
        reprehenderit?

      {% endblock content %}

    </div>

    <!-- Footer -->

    <div class="container-lg mt-auto">
      <hr>
      <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
          <p>
            <strong>Braniac</strong>
          </p>
          <p>
            <ul class="list-unstyled">
              <li><a href="{% url 'mainapp:main_page' %}">Домашняя</a></li>
              <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
              {% if user.is_authenticated %}
                <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
              {% else %}
                <li><a href="{% url 'authapp:login' %}">Войти</a></li>
              {% endif %}
            </ul>
          </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
          <p>
            <strong>Полезное</strong>
          </p>
          <p>
            <ul class="list-unstyled">
              <li><a href="#">Положения &amp; Условия</a></li>
              <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
              <li><a href="#">Документация по API</a></li>
              <li><a href="{% url 'mainapp:doc_site' %}">Документация по сайту</a>
              </li>
            </ul>
          </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
          <p>
            <strong>Мы в социальных сетях</strong>
          </p>
          <p>
            <div class="row justify-content-around">
              <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
              <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a>
              </div>
              <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a>
              </div>
              <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
          </p>
          <p>
            <strong>Наше приложение</strong>
          </p>
          <p>
            <div class="row justify-content-around">
              <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a>
              </div>
              <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
              <div><a href="#"><i class="fab fa-windows fa-2x"></i></a>
              </div>
            </div>
          </p>
        </div>
      </div>
      <div class="row justify-content-center">
        <div>
          <p><small>&copy; GeekBrains 2021</small></p>
        </div>
      </div>
    </div>

    <!-- /Footer -->




    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

    {% block js %}
      <script>
        $(document).ready(function () {

          {% if messages %}
            // Toasts
            $(".toast").toast({ delay: 5000 });
            $(".toast").toast("show");
          {% endif %}

        });
      </script>
    {% endblock js %}

  </body>

</html>